name: My first workflow
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "Hello world"
